### ISSUE TITLE
References to complex types from another namespace through bindings, breaks FluentBuilder

### ISSUE THREAD

**Issue by Danman85** [mklemm/jaxb-rich-contract-plugin#49]
Hello,

I am using your plugins in Gradle, in combination with [this plugin](https://github.com/nilsmagnus/wsdl2java). Like this:

**build.gradle:**
![image](https://user-images.githubusercontent.com/16355263/56016591-0a40a200-5cfd-11e9-89da-8339de02111f.png)

The xsd source are published by a third party, so I **cannot** change the xsd's in any way.
I use a bindings file to have some complex types built from a different namespace (nl.hl7.v3 instead of org.hl7.v3), since they are enhanced versions:

**bindings.jxb:**
![image](https://user-images.githubusercontent.com/16355263/56016748-95219c80-5cfd-11e9-9d8a-336ba9c8f67b.png)

Some of these referred types get extended by other types. As you can see in the .java source file below, RTOPQPQ (itself from namespace org.hl7.v3) extends PQ (nl.hl7.v3). 
_This snippet is generated without the FluentBuilder for illustrating purposes_

**org.hl7.v3.RTOPQPQ.java**
![image](https://user-images.githubusercontent.com/16355263/56021769-8beafc80-5d0a-11e9-9dbe-06337e16b68e.png)

The actual problem appears when I try to apply the FluentBuilder. Which reads as follows:
**Output**
![image](https://user-images.githubusercontent.com/16355263/56022653-75de3b80-5d0c-11e9-9045-e82d4e99416a.png)

With [this stacktrace](https://pastebin.com/fFmpDFyU)

Out of curiosity I did tweak the xsd's themselves to use the proper namespace references, negating the need to use a bindings file. Lo and behold!: the FluentBuilder works like a charm! 

Which leads me to the assumption that FluentBuilder is not taking into account the custom bindings for some reason. 

Is there something I am missing? Or is this a flaw in the FluentBuilder?

**Comment by mklemm** [comment]
This is certainly an error, because in some cases fluent-builder tries to find base classes itself, it doesn't take into account these modifications
