### ISSUE TITLE
Move package com.kscs.util.jaxb to own Maven module

### ISSUE THREAD

**Issue by jonnybecker** [mklemm/jaxb-rich-contract-plugin#55]
Hi,

would it be possible to move the package **com.kscs.util.jaxb** to an own Maven module, so I could provide this as a dependency for compile rather than the  the whole **jaxb2-rich-contract-plugin**  instead.

Another nice feature actually would be, to let the needed compile classes in **com.kscs.util.jaxb** be generated with a configurable namespace. This woulld be handy, since it would be possible to work with different versions of the **jaxb2-rich-contract-plugin** without possible clashes.

Regards
Jonny

**Comment by at055612** [comment]
By default the util classes are added alongside the generated jaxb classes (`-generateTools`).  The way we do it is for our generator gradle module to have the compile dependency on `jaxb2-rich-contract-plugin` so it can generate all the classes.  Our build then copies the generated classes and util classes into our api module.  We also have some code to re-package the util classes (I agree it would be nice if the plugin allowed you to define the package for the util classes) to put them in a more desirable package.  Our api module is then self contained with no dependencies on `jaxb2-rich-contract-plugin`.

**Comment by jonnybecker** [comment]
Thanks for coming back on this. 

I know the feature `-generateTools`. But our problem is, that we have **multiple modules** that we provide, which use the jaxb2-rich-contract-plugin. 
So for our purpose with generating the classes directly into the module, we wouldn't have track and generate clashes with more than one module using jaxb2-rich-contract-plugin.

**Comment by mklemm** [comment]
Will be fixed in 4.2.0. But please note that not all plugins need all utility classes. When you activate "generateTools", only the classes needed for the activated plugins are generated. A separate module would have to contain *all* of the possible dependencies, it would be getting to complicated otherwise...

**Comment by mklemm** [comment]
Fixed in 4.2.0.0
